language: node_js

cache: yarn

notifications:
  email: false

branches:
  only: 
    - master

jobs:
  include:
    - stage: build
      node_js: 
        - '8'
        - '9'
      script: yarn build

    - stage: release
      node_js: lts/*
      script: yarn build
      deploy:
        provider: script
        skip_cleanup: true
        script: yarn semantic-release

    - stage: deploy storybook
      if: type != push
      node_js: lts/*
      script: yarn deploy-storybook --ci

