language: node_js

cache: yarn

notifications:
  email: false

branches:
  only:
    - master

node_js: 
  - '8'
  - '9'

script: yarn build

jobs:
  include:
    - stage: release
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - yarn semantic-release
    - stage: deploy
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - yarn deploy-storybook --ci        

